### ISSUE TITLE
Acceptable formats not checked  when negotiating content type 

### ISSUE THREAD

**Issue by jong99** [ahmadnassri/restful-zend-framework#25]
If, in the config file I have:

```
rest.default = "json"
rest.formats[] = "json"
rest.formats[] = "xml"
```

And then I make a request with my browser, which sends the accept header:
```
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

Then I get an error as it tries to return text/html.  It should not return text/html, it should be XML based on the accept header above.

This seems to happen because https://github.com/codeinchaos/restful-zend-framework/blob/master/Controller/Plugin/RestHandler.php#L383 does not check to see if the response type being considered is actually in the variable ```$this->acceptableFormats```

This line instead seems to fix this issue:
```
            if (array_key_exists($type, $this->responseTypes) && !array_key_exists($quality, $mimeTypes) && in_array($this->responseTypes[$type], $this->acceptableFormats)) {
```

...or am I using it wrong?

**Comment by thompsa** [comment]
I have also hit this problem, the following patch resolves it for me. It unsets any mime types that are not supported to prevent them being negotiated.

```
Index: Controller/Plugin/RestHandler.php
===================================================================
--- Controller/Plugin/RestHandler.php	(revision 2107)
+++ lController/Plugin/RestHandler.php	(working copy)
@@ -93,6 +93,10 @@
         if ($rest) {
             $this->defaultFormat = $rest->default;
             $this->acceptableFormats = $rest->formats->toArray();
+            foreach($this->responseTypes as $mime => $format) {
+                if (!in_array($format, $this->acceptableFormats))
+                    unset($this->responseTypes[$mime]);
+            }
         }
     }
```

**Comment by ahmadnassri** [comment]
@thompsa thanks for the patch!
