### ISSUE TITLE
Probably a bug in REST_Controller_Plugin_RestHandler

### ISSUE THREAD

**Issue by virtuaris** [ahmadnassri/restful-zend-framework#30]
Hi there,
many thx for your work, nice lib!
Implementing a REST API i just noticed that using content-type xml as payload with a PUT/POST request hits the following code in class `REST_Controller_Plugin_RestHandler`, line 272 :

```
$_POST = (array) Zend_Json::decode($json, Zend_Json::TYPE_OBJECT)->request;
```

I'm wondering what that `request` is inteded for since Zend_Json::decode() returns a PHP stdClass representation of the json object $json and has no `request` property ?!
Cheers,
Harald

**Comment by ahmadnassri** [comment]
appologies, this repo is not actively maintained, I'm going to mark this repo as Archived.
